app:
  batch:
    # 한 번에 처리할 도서/이미지 작업의 개수
    size: 1000

spring:
  jpa:
    hibernate:
      ddl-auto: update # \uAC1C\uBC1C\uC6A9
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true     # SQL \uB85C\uADF8 \uBCF4\uAE30

    properties:
      hibernate:
        jdbc.batch_size: 1000 # 위에서 정의한 배치 크기 사용
        order_inserts: true   # 삽입 순서를 최적화
        order_updates: true   # 업데이트 순서를 최적화

        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  application:
    name: team3-booksearch
  # 1. 개별 파일의 최대 크기 (10MB)
  servlet:
    multipart:
      max-file-size: 10MB
  # 2. 전체 요청(JSON + 모든 파일)의 최대 크기 (50MB)
      max-request-size: 50MB


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


minio:
  url: http://storage.java21.net  # MiniIO 서버의 엔드포인트 주소
  accessKey: nhnacademy  # MiniIO 사용자 Access Key
  secretKey: nhnacademy123!  # MiniIO 사용자 Secret Key
  bucketName:
    book: book-image
    review: review-image
    test: book-cover