app:
  batch:
    # 한 번에 처리할 도서/이미지 작업의 개수
    size: 1000

spring:
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 1000 # 위에서 정의한 배치 크기 사용
        order_inserts: true   # 삽입 순서를 최적화
        order_updates: true   # 업데이트 순서를 최적화
  application:
    name: BooksSearch
  # 1. 개별 파일의 최대 크기 (10MB)
  servlet:
    multipart:
      max-file-size: 10MB
  # 2. 전체 요청(JSON + 모든 파일)의 최대 크기 (50MB)
      max-request-size: 50MB

minio:
  url: http://storage.java21.net  # MiniIO 서버의 엔드포인트 주소
  accessKey: nhnacademy  # MiniIO 사용자 Access Key
  secretKey: nhnacademy123!  # MiniIO 사용자 Secret Key
  bucketName:
    book: book-image
    review: review-image
    test: book-cover