server:
  port: 8088

  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: team3-booksearch
  datasource:
#    url: jdbc:mysql://220.67.216.14:13306/nhn_exam_8?serverTimezone=Asia/Seoul
    url: jdbc:mysql://s4.java21.net:13306/project_be12_team3?serverTimezone=Asia/Seoul
    username: project_be12_team3
    password: Vu52gc0i(mNxDJyI
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: '*N2vya7H@muDTwdNMR!'
      database: 379

  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
    hibernate:
      ddl-auto: update # \uAC1C\uBC1C\uC6A9
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false # SQL \uB85C\uADF8 \uBCF4\uAE30

  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: "nhnacademy123!"
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          multiplier: 2.0
    virtual-host: /team3_order

aladin:
  ttb-key: "ttbhoban01031805001"
  api-url: "http://www.aladin.co.kr/ttb/api/ItemLookUp.aspx"

rabbitmq:
  queue:
    book: team3.saga.book.queue.v2.dev
  routing:
    confirmed: order.confirmed.v2.dev
    deducted: inventory.deducted.dev

app:
  ai:
    gemini-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    gemini-api-key: AIzaSyCAoVKNQt33ADPHpif2SFvKIO6qHiUtZbo

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: false
  zipkin:
    tracing:
      export:
        enabled: false
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    org:
      springframework:
        web: INFO
      # For Lazy Loading Test
      hibernate:
        SQL: INFO
        orm:
          jdbc:
            bind: INFO

minio:
  url: http://storage.java21.net:8000  # MiniIO 서버의 엔드포인트 주소
  accessKey: tUQ5cvl8WJSqBDwtqWAW  # MiniIO 사용자 Access Key
  secretKey: ufyZgbYaKPG2Syfv4C0CExifq7B4z8ZzzCndGX2c  # MiniIO 사용자 Secret Key
  bucketName:
    book: daiso-book-cover
    review: daiso-review-image
    test: daiso-book-image
#    test: daiso-book-cover
