server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    connection-timeout: 120s

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: Book-Service-Pool
      maximum-pool-size: 20       # 기본 10개에서 20개로 상향
      minimum-idle: 20            # 미리 20개를 다 만들어 두어(Warm-up) 첫 요청 지연 방지
      connection-timeout: 3000     # 커넥션 획득 대기 시간을 3초로 제한
      idle-timeout: 600000
      max-lifetime: 1800000        # 커넥션 최대 수명 (30분)
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false
    hibernate.ddl-auto: update
    hibernate:
      ddl-auto: update # \uAC1C\uBC1C\uC6A9
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true     # SQL \uB85C\uADF8 \uBCF4\uAE30
  servlet:
    multipart:
      max-request-size: 20MB
#  elasticsearch:
#    uris: http://s4.java21.net:9200
#    username: elastic
#    password: nhnacademy123!
#    socket-timeout: 60s
#    connection-timeout: 5s
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: '*N2vya7H@muDTwdNMR!'
      database: 379
    jpa:
      repositories:
        bootstrap-mode: default
      elasticsearch:
        repositories:
          enabled: true # 이 설정은 유지하되 DataConfig에서 범위를 제한함
  ai:
    gemini-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    gemini-api-key: AIzaSyAmSu5Ur0hOJoD6BJQycni8x9-m614vZ3k

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          multiplier: 2.0


rabbitmq:
  exchange:
    main: team3.booksearch.exchange
    retry: team3.booksearch.retry.dlx
    dlx: team3.booksearch.dlx
  queue:
    ai-analysis: team3.booksearch.ai.analysis.queue
    book-upsert: team3.booksearch.book.upsert.queue
    book-delete: team3.booksearch.book.delete.queue
    book: team3.saga.book.queue.v2

  routing:
    ai-analysis: team3.booksearch.ai.analysis
    ai-analysis-retry: team3.booksearch.ai.analysis.retry
    ai-analysis-fail: team3.booksearch.ai.analysis.fail

    book-upsert: team3.booksearch.book.upsert
    book-upsert-retry: team3.booksearch.book.upsert.retry
    book-upsert-fail: team3.booksearch.book.upsert.fail

    book-delete: team3.booksearch.book.delete
    book-delete-retry: team3.booksearch.book.delete.retry
    book-delete-fail: team3.booksearch.book.delete.fail

    confirmed: order.confirmed.v2
    deducted: inventory.deducted



app:
  batch:
    size: 1000
#  ai:
#    embedding-url: http://ollama.java21.net/api/embeddings
#    reranker-url: http://reranker.java21.net/rerank
#    gemini-api-key: AIzaSyAPjRTWLiLXhJBCiCKoCNi3aPVMNGkU4go
#    gemini-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
#    com.zaxxer.hikari: DEBUG  # 히카리 상세 로그 활성화
#    com.zaxxer.hikari.HikariConfig: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

minio:
  url: http://storage.java21.net:8000  # MiniIO 서버의 엔드포인트 주소
  accessKey: tUQ5cvl8WJSqBDwtqWAW  # MiniIO 사용자 Access Key
  secretKey: ufyZgbYaKPG2Syfv4C0CExifq7B4z8ZzzCndGX2c  # MiniIO 사용자 Secret Key
  bucketName:
    book: daiso-book-cover
    review: daiso-review-image
    test: daiso-book-image
#    test: daiso-book-cover