server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    connection-timeout: 120s

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
    open-in-view: false
    hibernate.ddl-auto: update
    hibernate:
      ddl-auto: update # \uAC1C\uBC1C\uC6A9
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true     # SQL \uB85C\uADF8 \uBCF4\uAE30
  servlet:
    multipart:
      max-request-size: 20MB
  elasticsearch:
    uris: http://s4.java21.net:9200
    username: elastic
    password: nhnacademy123!
    socket-timeout: 60s
    connection-timeout: 5s
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: '*N2vya7H@muDTwdNMR!'
      database: 379


  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

app:
  batch:
    size: 1000
  ai:
    embedding-url: http://ollama.java21.net/api/embeddings
    reranker-url: http://reranker.java21.net/rerank
    gemini-api-key: AIzaSyAPjRTWLiLXhJBCiCKoCNi3aPVMNGkU4go
    gemini-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

minio:
  url: http://storage.java21.net:8000  # MiniIO 서버의 엔드포인트 주소
  accessKey: tUQ5cvl8WJSqBDwtqWAW  # MiniIO 사용자 Access Key
  secretKey: ufyZgbYaKPG2Syfv4C0CExifq7B4z8ZzzCndGX2c  # MiniIO 사용자 Secret Key
  bucketName:
    book: daiso-book-image
    review: daiso-review-image
    test: daiso-book-cover