server:
  port: 8088

  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: team3-booksearch
  datasource:
#    url: jdbc:mysql://220.67.216.14:13306/nhn_exam_8?serverTimezone=Asia/Seoul
    url: jdbc:mysql://s4.java21.net:13306/project_be12_team3?serverTimezone=Asia/Seoul
    username: project_be12_team3
    password: Vu52gc0i(mNxDJyI
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
    hibernate:
      ddl-auto: update # \uAC1C\uBC1C\uC6A9
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true     # SQL \uB85C\uADF8 \uBCF4\uAE30

#  rabbitmq:
#    host: ${SPRING_RABBITMQ_HOST}
#    port: ${SPRING_RABBITMQ_PORT}
#    username: ${SPRING_RABBITMQ_USERNAME}
#    password: ${SPRING_RABBITMQ_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


minio:
  url: http://storage.java21.net:8000  # MiniIO 서버의 엔드포인트 주소
  accessKey: tUQ5cvl8WJSqBDwtqWAW  # MiniIO 사용자 Access Key
  secretKey: ufyZgbYaKPG2Syfv4C0CExifq7B4z8ZzzCndGX2c  # MiniIO 사용자 Secret Key
  bucketName:
    book: daiso-book-image
    review: daiso-review-image
    test: daiso-book-cover